Repository rapidsai/ucx-wheels, pull requests merged in 2024-05, with the labels that each got.

#4 Build v1.16.0
  VERSION
Labels: breaking, feature request

#7 publish v1.16.0.post1
  VERSION
Labels: bug, non-breaking

#8 add pre-commit checks
  .github/workflows/build_and_test.yaml
  .pre-commit-config.yaml
  README.md
  python/libucx/libucx/__init__.py
  python/libucx/libucx/load.py
  python/libucx/setup.py
Labels: improvement, non-breaking
